# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeldPackageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=40)),
                ('currentver', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='InstalledPackageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=60)),
                ('currentver', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='UpdateablePackageList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(max_length=40)),
                ('currentver', models.CharField(max_length=60)),
                ('newver', models.CharField(max_length=60)),
            ],
        ),
    ]
