# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 14:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeldPackageList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=40)),
                ('currentver', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='HostInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=50)),
                ('os_name', models.CharField(max_length=40)),
                ('os_version', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Hosts',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hostaddr', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstalledPackageList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=60)),
                ('currentver', models.CharField(max_length=60)),
                ('host_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Hosts')),
            ],
        ),
        migrations.CreateModel(
            name='UpdateablePackageList',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('package', models.CharField(max_length=40)),
                ('currentver', models.CharField(max_length=60)),
                ('newver', models.CharField(max_length=60)),
                ('host_addr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Hosts')),
            ],
        ),
        migrations.AddField(
            model_name='hostinfo',
            name='host_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Hosts'),
        ),
        migrations.AddField(
            model_name='heldpackagelist',
            name='host_addr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.Hosts'),
        ),
    ]
