# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-28 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostinfo',
            name='host_address',
            field=models.CharField(max_length=50),
        ),
    ]
