# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_auto_20170528_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosts',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
